# Generated by Django 6.0.4 on 2026-04-28 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vehicle_types',
            field=models.ManyToManyField(to='vehicles.vehicletype'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['provider', 'is_active'], name='services_provide_c85dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='services_categor_a61a21_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['rating'], name='services_rating_457b8d_idx'),
        ),
    ]
