# Generated by Django 6.0.4 on 2026-04-28 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='towtruck',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tow_trucks', to='providers.providerprofile'),
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['availability_status'], name='provider_pr_availab_35b22e_idx'),
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['rating'], name='provider_pr_rating_77e79a_idx'),
        ),
        migrations.AddIndex(
            model_name='towtruck',
            index=models.Index(fields=['status'], name='tow_trucks_status_4a3ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='towtruck',
            index=models.Index(fields=['plate_number'], name='tow_trucks_plate_n_bb3903_idx'),
        ),
    ]
